### ISSUE TITLE
有关assignment1-3

### ISSUE THREAD

**Issue by jinglearnai** [bighuang624/Andrew-Ng-Deep-Learning-notes#1]
我下载你在github上这个任务里在做第一课的第三次作业的时候遇到一些问题，不知道怎么处理，能帮我看一下么
问题1
以下截图1是运行到前面可视化数据的时候出现的问题
![00](https://user-images.githubusercontent.com/36097737/35766220-83805abe-090e-11e8-94d3-2a091169a58c.png)
这个问题我再网易课程的论坛中也找到了解决方法，将其中的代码c=Y修改成c=Y[0,]既可以看到那个花型图案，但是我在csdn以及github的网站上看到运行代码这里都不需要修改还是能够运行出花型图案，包括下载到您的代码我看到运行结果在没有修改代码的时候也运行出结果了，所以我想问下这里是我的环境有什么问题么？

问题2
![02](https://user-images.githubusercontent.com/36097737/35766241-22ccc24c-090f-11e8-96d1-e2e73e6a5e2a.png)
运行这个cell会有下面红色的一行字体，您的运行结果也是有的，但是看到其他一些人的结果并没有这些红色字体，所以这里是为什么呢？不影响我们后续的运行么

问题3
![01](https://user-images.githubusercontent.com/36097737/35766249-6fdcb330-090f-11e8-836b-deaea1ae4e68.png)
这个运行又是为什么，我在网上搜到所有人都能正常的运行出结果，但是我这里却总是报这个错误，不知道为什么出错？？？

希望能帮忙看一下，初次介入deeplearning领域，也是刚刚学着使用github，周围没有可以参考的人，冒昧的打扰您，希望能帮忙处理一下

**Comment by bighuang624** [comment]
@jinglearnai  不好意思才看到，不知道你是否已经解决了这些问题。
关于第二个问题，这些警告出现的原因有很多，例如使用的方法在包的下个版本预定被删除、方法使用方式不标准等等。但既然没报错，就不影响后续运行；
第一、第三个问题，我不是很了解。看报错信息和 numpy.ndarray 数据类型有关，并且错误发生在同一个包的同一个方法，**不负责任地猜测**是某些包（matplotlib）的安装出了问题（bug 是玄学问题）？
我学习 Python 的时间也不长，不好意思没法全部解答你的问题。
