### ISSUE TITLE
mistakes in assignments/assignment2-1/3.Gradient+Checking.ipynb

### ISSUE THREAD

**Issue by starFalll** [bighuang624/Andrew-Ng-Deep-Learning-notes#10]
What you wrote is 
>There is a mistake in the backward propagation! difference = 0.17344196893145933
>和预期有差别。暂不知道原因

Your codes:
```
dA2 = np.dot(W3.T, dZ3)
    dZ2 = np.multiply(dA2, np.int64(A2 > 0))
    dW2 = 1./m * np.dot(dZ2, A1.T) * 2 #It was wrong
    db2 = 1./m * np.sum(dZ2, axis=1, keepdims = True)
    
    dA1 = np.dot(W2.T, dZ2)
    dZ1 = np.multiply(dA1, np.int64(A1 > 0))
    dW1 = 1./m * np.dot(dZ1, X.T)
    db1 = 1./m * np.sum(dZ1, axis=1, keepdims = True)
```
This line `dW2 = 1./m * np.dot(dZ2, A1.T) * 2 `  was wrong.
In this exercise,this piece of code was originally like this(maybe you have chenged some codes,but you did not konw)
```
dA2 = np.dot(W3.T, dZ3)
    dZ2 = np.multiply(dA2, np.int64(A2 > 0))
    dW2 = 1./m * np.dot(dZ2, A1.T) * 2 #wrong
    db2 = 1./m * np.sum(dZ2, axis=1, keepdims = True)
    
    dA1 = np.dot(W2.T, dZ2)
    dZ1 = np.multiply(dA1, np.int64(A1 > 0))
    dW1 = 1./m * np.dot(dZ1, X.T)
    db1 = 4./m * np.sum(dZ1, axis=1, keepdims = True) #wrong
```
There were errors in the backward_propagation_n code.
The code should be modified to:
```
dA2 = np.dot(W3.T, dZ3)
    dZ2 = np.multiply(dA2, np.int64(A2 > 0))
    dW2 = 1./m * np.dot(dZ2, A1.T) 
    db2 = 1./m * np.sum(dZ2, axis=1, keepdims = True)
    
    dA1 = np.dot(W2.T, dZ2)
    dZ1 = np.multiply(dA1, np.int64(A1 > 0))
    dW1 = 1./m * np.dot(dZ1, X.T)
    db1 = 1./m * np.sum(dZ1, axis=1, keepdims = True)
```

**Comment by bighuang624** [comment]
@starFalll Thanks for your issue. I was preparing my final exams so I process this late. However, I found the result still dismatched the given one. The difference now becomes `1.1890913024375147e-07`. And I' m sure I changed it as you suggested. I believe that your suggestion is correct, but I 'm wondering why the result doesn't match.

**Comment by starFalll** [comment]
@bighuang624 My answer is **Your backward propagation works perfectly fine! difference = 1.18904178788e-07**. So you got the correct answer.

**Comment by bighuang624** [comment]
@starFalll OK. Thanks.
