### ISSUE TITLE
神经网络和深度学习-浅层神经网络 - 计算神经网络的输出，关于W的shape的问题

### ISSUE THREAD

**Issue by kite8** [bighuang624/Andrew-Ng-Deep-Learning-notes#13]
[原文链接](http://kyonhuang.top/Andrew-Ng-Deep-Learning-notes/#/Neural_Networks_and_Deep_Learning/浅层神经网络)
Z1 = W1.T * a0 + b1
因为
input layer = 3
hidden layer = 4
output layer = 1
所以，a0的shape是(3,1), 那么W1.T的shape推得即为(4,3)，所以W1的shape是(3,4)，同理W2的shape也应该反过来才是

补充:看到后面的[神经网络的梯度下降法]中forward propagation中Z1 = W1 * X + b，这里没有转置，建议前后统一，我担心有对向量化不熟的童鞋，这里会晕掉

**Comment by bighuang624** [comment]
@kite8  谢谢。吴恩达老师的课程在这几处本身写的不太清楚，当时就照着写了，现在看来理应修改。
