### ISSUE TITLE
感谢作者，但数学公式都无法显示

### ISSUE THREAD

**Issue by AlexJJYY** [bighuang624/Andrew-Ng-Deep-Learning-notes#15]
无论在github中还是html在线阅读，数学公式都无法正常显示，十分影响学习和阅读！不知能够改进？

**Comment by bighuang624** [comment]
@AlexJJYY  我现在看 html 在线阅读是可以显示的。你看到无法正常显示的原因大概率是网络问题导致 MathJax 的 javascript 脚本没有加载出来。

![unnamed](https://user-images.githubusercontent.com/18595460/55385339-7a159680-555f-11e9-9d8d-91a90f7081d3.png)

**Comment by bighuang624** [comment]
@AlexJJYY  至于在 markdown 文件中，github 没办法把公式显示为正确的样子。如果确实在网络比较稳定时公式仍然无法加载，可以尝试以下方法：将整个项目 clone 下来，在你想阅读的 markdown 文件的最后加上这几行代码：

```html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [ ['$', '$'] ],
        displayMath: [ ['$$', '$$']]}
});
</script>

<script type="text/javascript" src="https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=default"></script>
```

其中，`https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=default`可以换成任何你可以加载的 MathJax.js 的 cdn，或者改成本地放置 MathJax.js 脚本的路径。这样，该 markdown 文件的公式应该可以在 MacDown 等专业 markdown 编辑器中正确显示。

**Comment by AlexJJYY** [comment]
> @AlexJJYY 我现在看 html 在线阅读是可以显示的。你看到无法正常显示的原因大概率是网络问题导致 MathJax 的 javascript 脚本没有加载出来。
> 
> ![unnamed](https://user-images.githubusercontent.com/18595460/55385339-7a159680-555f-11e9-9d8d-91a90f7081d3.png)

感谢感谢，已经解决，应该是网络问题！
