### ISSUE TITLE
Word2Vec模型概念模糊

### ISSUE THREAD

**Issue by lhaippp** [bighuang624/Andrew-Ng-Deep-Learning-notes#19]
SG的概念定义的比较模糊
SKip-gram：抽取上下文(context)和目标词(target)配对
例：orange(上下文) juice(目标)

**Comment by bighuang624** [comment]
@lhaippp 是要举个例子说明什么是 context 什么是 target 的意思吗

**Comment by lhaippp** [comment]
你的原文是：**根据词预测目标上下文**
我觉得这里把上下文(context)和目标(target)这两个概念混淆在一起了，而这两个概念应该独立并且阐述他们的主次关系
比如改成：根据上下文(context)预测目标(target)

**Comment by lhaippp** [comment]
当然如果可以加一些例子说明会更好
谢谢
