### ISSUE TITLE
assignment1-2     2_2

### ISSUE THREAD

**Issue by yikayiyo** [bighuang624/Andrew-Ng-Deep-Learning-notes#2]
做预测时模型参数应该是训练得到的参数
predict(w,b,X)  改为 
predict(params['w'],params['b'],X)

**Comment by bighuang624** [comment]
@yikayiyo  不好意思才看到，是这里吗？还有别的地方吗？
![error.jpg](http://upload-images.jianshu.io/upload_images/2702529-777cf0e58905cd7c.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by yikayiyo** [comment]
@bighuang624 辛苦了-0-
