### ISSUE TITLE
Xavier initialization处有误

### ISSUE THREAD

**Issue by brealisty** [bighuang624/Andrew-Ng-Deep-Learning-notes#23]
WL = np.random.randn(WL.shape[0], WL.shape[1]) * np.sqrt(1/n)
这样，激活函数的输入 x 近似设置成均值为 0，标准方差为 1，

这里np.random.randn是 均值0，方差1的分布，乘上sqrt(1/n)，根据方差公式推导，方差=1/n，对应的标准差=sqrt(1/n)

**Comment by bighuang624** [comment]
@brealisty 我好像没有太理解你想表达的错误在哪。我感觉你将模型参数`WL` 理解为后文的“激活函数的输入 x”了？
如果你觉得我理解的不对，欢迎继续指出。最好是能够告诉我你觉得原文哪些地方应该具体修改成什么样。

**Comment by brealisty** [comment]
> @brealisty 我好像没有太理解你想表达的错误在哪。我感觉你将模型参数`WL` 理解为后文的“激活函数的输入 x”了？
> 如果你觉得我理解的不对，欢迎继续指出。最好是能够告诉我你觉得原文哪些地方应该具体修改成什么样。

哦，抱歉是我看差了。那这里激活函数的输入x标准方差为1，这里怎么理解呢？如何推导？

**Comment by bighuang624** [comment]
@brealisty  我的理解是，这就是一个前提的假设。如果我把原文改为`这样，“当”激活函数的输入 x 近似设置成均值为 0，标准差为 1“时”，神经元输出 z 的方差就正则化到 1 了`，是否会更好？
