### ISSUE TITLE
RMSProp 算法的一点建议

### ISSUE THREAD

**Issue by kuangxiaoye** [bighuang624/Andrew-Ng-Deep-Learning-notes#24]
RMSProp 算法 写的和老师讲的有一点出入 

dw那组方程变小  db组方程变大

才能实现纵向变小 横向变快 

比写同时变大会更好一点吧

**Comment by bighuang624** [comment]
@kuangxiaoye  感谢指正。这块当初写的确实不是很好理解，已经修改。

**Comment by kuangxiaoye** [comment]
感谢你的笔记  希望他能更加完善 帮助到更多人 😀
