### ISSUE TITLE
一些公式的问题好像有些错误

### ISSUE THREAD

**Issue by RexKing6** [bighuang624/Andrew-Ng-Deep-Learning-notes#3]
在第二课：改善深层神经网络：超参数调试、正则化以及优化的第二周优化算法里的“理解指数平均加权”的展开式latex公式貌似没写对，直接显示的latex源码。
然后在指数平均加权的偏差修正中的公式的右式也应该除以1-\beta^t，不然老以为得将左式分母，移到右式。
另外，十分感谢您的笔记，对我的学习起了很大的帮助！

**Comment by bighuang624** [comment]
@RexKing6 
均已修改，可以看一下。谢谢反馈！

**Comment by RexKing6** [comment]
嗯嗯，同时还有学习率衰减的第一条公式，也是显示的latex源码。

**Comment by bighuang624** [comment]
@RexKing6  好的。都是因为`*`能够直接在我本地 md 编辑器直接显示，忘记加`\`导致的。这处也已经修正了，下次 commit 就会更新。谢谢！

**Comment by RexKing6** [comment]
嗯嗯，据我所知，博客换个渲染框架，之后再修改其中关于转义的正则表达式应该能解决你所说的问题。

**Comment by RexKing6** [comment]
你好，我怕一下回一条太过打扰了，作了一下记录。
深度学习笔记勘误：
1. 卷积神经网络.填充.滤波器大小少打f
2. 同上，在第一张图后的滤波器大小少打f
3. 同上，在卷积步长小节滤波器大小少打f

再次谢谢你的笔记，帮了我很多！
卷积神经网络和序列模型的中文字幕基本都有了。
互相学习，一起进步呀！

**Comment by bighuang624** [comment]
@RexKing6  手抖了，非常感谢。最近在做情感分析的项目，因此打算先把序列模型那部分啃完。
