### ISSUE TITLE
知识点是否都覆盖了呢？

### ISSUE THREAD

**Issue by adaaaaaa** [bighuang624/Andrew-Ng-Deep-Learning-notes#7]
看起来不错，但是，我想就单单靠通过复习你的笔记来通过深度学习课程的所有选择题测试，是否可靠？

**Comment by bighuang624** [comment]
@adaaaaaa 不保证全部覆盖（虽然我觉得没漏掉什么重要的知识点）。笔记本来就是个比较私人化的东西。

**Comment by adaaaaaa** [comment]
大佬，你既然开源了。。。还是尽量做好点吧？私人的东西就不要开源算了。。。

**Comment by bighuang624** [comment]
@adaaaaaa 
1. 我没说我没打算做好；
2. “私人化”意指，如果某个知识点我是非常熟的，笔墨较少或者略过都是可能的。笔记仅供参考，不是讲义，也不能替代老师的课程；
3. 能不能“单单靠通过复习你的笔记来通过深度学习课程的所有选择题测试”，这不是我能决定的，毕竟不是我在做题。
