### ISSUE TITLE
笔记小错误-正则化

### ISSUE THREAD

**Issue by yikayiyo** [bighuang624/Andrew-Ng-Deep-Learning-notes#8]
正则化是在成本函数中加入一个正则化项，惩罚模型的复杂度。正则化可以用于解决**低方差**的问题。
权重衰减这里：(1−αλ/m)W[l]<1-----是不是应该是(1−αλ/m)W[l]<W[l]

**Comment by chsl** [comment]
正则化用于减少过拟合的问题，应该是解决**高方差**的问题吧？

**Comment by yikayiyo** [comment]
@chsl 对

**Comment by bighuang624** [comment]
@yikayiyo @chsl  收到。两处笔误。

**Comment by bighuang624** [comment]
话说我一开始盯着那个“方差”几分钟...在考虑是不是应该是偏差...没想到是这么低级的错误OTZ
