### ISSUE TITLE
week 2 编程作业

### ISSUE THREAD

**Issue by OhGarrys** [bighuang624/Andrew-Ng-Deep-Learning-notes#9]
我用的是jupyter notebook.在第二周的编程作业中，我在加载数据的时候会报出打开不了.h5这个文件，如下：
#Loading the data (cat/non-cat)
train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()
----------------------------------------------------------------------------------------------------
OSError Traceback (most recent call last)
in ()
1 # Loading the data (cat/non-cat)
----> 2 train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()

~\lr_utils.py in load_dataset()
4
5 def load_dataset():
----> 6 train_dataset = h5py.File('train_catvnoncat.h5', "r")
7 train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
8 train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

d:\asoftware\python-3.5.4\benti\lib\site-packages\h5py_hl\files.py in init(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
267 with phil:
268 fapl = make_fapl(driver, libver, **kwds)
--> 269 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
270
271 if swmr_support:

d:\asoftware\python-3.5.4\benti\lib\site-packages\h5py_hl\files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
97 if swmr and swmr_support:
98 flags |= h5f.ACC_SWMR_READ
---> 99 fid = h5f.open(name, flags, fapl=fapl)
100 elif mode == 'r+':
101 fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py_objects.pyx in h5py._objects.with_phil.wrapper()

h5py_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'datasets/train_catvnoncat.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by OhGarrys** [comment]
我是直接把.h5 这个文件丢在和代码同一个目录下的，因为是第一次用jupyter notebook ,我不知道是否是因为使用不当造成错误 如果能帮上我真的十分感谢

**Comment by OhGarrys** [comment]
另外我有尝试新建一个文件用来测试能否打开.h5这个文件是成功了的，所以这就导致我更加迷糊了 代码如下

**Comment by OhGarrys** [comment]
import h5py
import numpy as np
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"
# 打开文件
train_dataset= h5py.File('train_catvnoncat.h5', 'r')

train_dataset.keys()
# Direct calling keys will get the following output
# Which can not determin what's inside
# KeysView(<HDF5 file "train_catvnoncat.h5" (mode r)>)
# While we could loop over it
for key in train_dataset.keys():
    print(key)

child_keys = [k for k in train_dataset.keys()]
-------------------------------------------------------------
list_classes
train_set_x
train_set_y
-----------------------------------------
all_child_keys = []
train_dataset.visit(all_child_keys.append)
train_dataset['train_set_x'][:]
--------------------------------------------------
array([[[[ 17,  31,  56],
         [ 22,  33,  59],
         [ 25,  35,  62],
         ...,
         [  1,  28,  57],
         [  1,  26,  56],
         [  1,  22,  51]],

        [[ 25,  36,  62],
         [ 28,  38,  64],
         [ 30,  40,  67],
         ...,
         [  1,  27,  56],
         [  1,  25,  55],
         [  2,  21,  51]],

        [[ 32,  40,  67],
         [ 34,  42,  69],
         [ 35,  42,  70],
         ...,
         [  1,  25,  55],
         [  0,  24,  54],
         [  1,  21,  51]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]]]], dtype=uint8)

**Comment by OhGarrys** [comment]
@honghu-zero

**Comment by bighuang624** [comment]
@OhGarrys  建议参考[assignments/assignment1-2](https://github.com/bighuang624/Andrew-Ng-Deep-Learning-notes/tree/master/assignments/assignment1-2)，将 h5 文件放在 datasets 文件夹中，并注意 lr_utils.py 中填写的文件路径。

**Comment by OhGarrys** [comment]
真的十分感谢，这个问题我已经解决了，谢谢你的回答
